bloggerblog_login:
    path:     /login
    defaults: { _controller: bloggerblogBundle:Default:login}

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

bloggerblog_showBlogList:
    path:     /showBlogList/{start}
    defaults: { _controller: bloggerblogBundle:Default:showBlogList,start : 1}

bloggerblog_blog_masterAdmin:
    resource: "@bloggerblogBundle/Resources/config/master_admin.yml"
    prefix: /master_admin

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /editProfile

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile