bloggerblog_blogHomepage:
    path:     /
    host:     "{blog_name}.blog"
    defaults: { _controller: bloggerblogBundle:blog:blog}
bloggerblog_blogArticle:
    path:     /{article_name}
    host:     "{blog_name}.blog"
    defaults: { _controller: bloggerblogBundle:blog:article }
bloggerblog_homepage:
    path:     /
    defaults: { _controller: bloggerblogBundle:Default:index}