bloggerblog_blogHomepage:
    path:     /
    host:     "{blog_name}.blog"
    defaults: { _controller: bloggerblogBundle:blog:blog}
bloggerblog_blogArticle:
    path:     /{article_name}
    host:     "{blog_name}.blog"
    defaults: { _controller: bloggerblogBundle:blog:article }
bloggerblog_homepage:
    path:     /
    defaults: { _controller: bloggerblogBundle:Default:index}
bloggerblog_blogSuperAdmin:
    path:     /admin/showArticles
    defaults: { _controller: bloggerblogBundle:adminBlog:dashboard}
bloggerblog_blogAdmin:
    path:     /admin/
    defaults: { _controller: bloggerblogBundle:adminBlog:dashboard}
bloggerblog_blogAdminAddArticle:
    path:     /admin/addArticle
    defaults: { _controller: bloggerblogBundle:adminBlog:addArticle}
bloggerblog_blogAdminShowRecentArticles:
    path:     /admin/showRecentArticles
    defaults: { _controller: bloggerblogBundle:adminBlog:showRecentArticles}
bloggerblog_blogAdminRemoveArticle:
    path:     /admin/removeArticle/{address}
    defaults: { _controller: bloggerblogBundle:adminBlog:removeArticle}
bloggerblog_blogAdminEditArticle:
    path:     /admin/editArticle/{address}
    defaults: { _controller: bloggerblogBundle:adminBlog:editArticle}
