bloggerblog_homepage:
    path:     /
    defaults: { _controller: bloggerblogBundle:Default:index}

bloggerblog_page:
    resource: "@bloggerblogBundle/Resources/config/page.yml"
    prefix: /page

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

bloggerblog_blogAdmin:
    resource: "@bloggerblogBundle/Resources/config/admin.yml"
    prefix: /admin

bloggerblog_blogHomepage:
    path:     /{blog_name}/{start}
#    host:     "{blog_name}.blog"
    defaults: { _controller: bloggerblogBundle:blog:blog,start : 1}

bloggerblog_blogArticle:
    path:     /{blog_name}/post/{article_name}
#    host:     "{blog_name}.blog"
    defaults: { _controller: bloggerblogBundle:blog:article }

#bloggerblog_blogArticle_newComment:
#    path:     /{blog_name}/post/{article_name}
#    methods
##    host:     "{blog_name}.blog"
#    defaults: { _controller: bloggerblogBundle:blog:article }