parameters:
#    bloggerblog.example.class: blogger\blogBundle\Example

services:
  acme_blog.registration.form.type:
      class: blogger\blogBundle\Form\RegistrationFormType
      arguments: [%fos_user.model.user.class%]
      tags:
          - { name: form.type, alias: blog_user_registration }

  authentication_handler:
      class: blogger\blogBundle\Handler\AuthenticationHandler
      arguments: [@router, @security.context]

#    bloggerblog.example:
#        class: %bloggerblog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  my_date_convert:
      class: Hotel\reserveBundle\Handler\DateConvertor
      arguments: [@ce.jalali_date.date_converter,@ce.jalali_date.date_time]
