parameters:
#    bloggerblog.example.class: blogger\blogBundle\Example

services:
#    bloggerblog.example:
#        class: %bloggerblog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
